# Generated by Django 4.1.5 on 2023-01-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('key_skills', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('salary', models.IntegerField(blank=True, default=0, null=True)),
                ('area_name', models.CharField(default='', max_length=100)),
                ('published_at', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Vacancy',
                'verbose_name_plural': 'Vacancies',
            },
        ),
    ]
